### ISSUE TITLE
OOD-ify Job Constructor

### ISSUE THREAD

**Issue by ericfranz** [OSC/ood-myjobs#157]
OSC specific items in job constructor:

1. use of osc-machete which auto-sets Account String to primary group 

Torque specific items in job constructor:

1. osc-machete's default job adapter uses torque
2. when filtering list of clusters to use, we do this: <br>`c.resource_mgr_server.is_a?(OodCluster::Servers::Torque)`<br>https://github.com/AweSim-OSC/osc-jobconstructor/blob/f11798a42816aa7d558502a840ab028ce860ad30/config/initializers/ood_appkit.rb#L

Minimal steps to remove OSC specific items (but retain Torque Specific items):

- [x] 1. Apply the fix to update_status https://github.com/AweSim-OSC/documentation/wiki/Port-an-existing-app-to-OOD#5-explicitly-update-status-of-jobs-on-each-request
- [x] 2. Create a OSC::Machete::TorqueAdapter that uses ood_job gem object to pass into all places OSC::Machete::Job.new is called: Workflow#build_jobs and Job#job https://github.com/OSC/osc_machete_rails/blob/57b19d30eccb748162f11f9e4501319a137a0860/lib/osc_machete_rails/statusable.rb#L123-L125 
- [x] 3. Add custom Account String field to Job Options for jobs and save this in the Workflow#job_attrs. The custom OSC::Machete::TorqueAdapter that uses ood_job should have the custom script attributes added here
- [x] 3a. Display Account string and helpful information in detail pane
- [x] 4. Remove OSC specific job templates from the app into a separate repo which are both OSC and Torque specific
- [x] 5.  Ensure app works when templates directory is empty or does not exist
- [x] 6. Update error messages in osc_machete_rails to say "An error occurred" instead of "A PBS::Error occurred" https://github.com/OSC/osc_machete_rails/blob/57b19d30eccb748162f11f9e4501319a137a0860/lib/osc_machete_rails/workflow.rb#L116-L122 - not doing now - mentioned in https://github.com/AweSim-OSC/osc-jobconstructor/issues/159
- [x] 7. Revisit "updating workflows before delete". https://github.com/OSC/ood_job/issues/8 _its a hard problem_
